name: mcmc_env
channels:
    - jgomezdans
    - conda-forge

dependencies:
    - python
    - jupyter
    - numpy
    - scipy
    - matplotlib
    - prosail
    - seaborn
    - ipywidgets
    - jupyterlab
    - notebook
    - ipykernel
    - ipywidgets
    - ipyleaflet
    - pandas
    - gdal
    - tqdm
    - libgdal
    - netCDF4
    - pip
    - pip:
        - pcse
        - git+https://github.com/jgomezdans/GomezEngine
        - git+https://github.com/jgomezdans/gp_emulator
