name: multiply 
channels:
    - conda-forge
dependencies:
    - python<=3.10
    - numpy
    - scipy
    - jupyterlab
    - matplotlib-base
    - matplotlib-inline
    - ipywidgets
    - ipykernel
    - ipympl
    - ipywidgets
    - ipyleaflet
    - pandas
    - tqdm
    - seaborn
    - pip
    - pip:
        - pcse
        - https://github.com/jgomezdans/gp_emulator/archive/refs/tags/1.6.5.zip
        - prosail
