name: mcmc_env
channels:
    - conda-forge
dependencies:
    - python<=3.10
    - numpy
    - scipy
    - matplotlib
    - seaborn
    - ipywidgets
    - ipykernel
    - ipywidgets
    - ipyleaflet
    - pandas
    - gdal
    - tqdm
    - libgdal
    - netCDF4
    - pip
    - pip:
        - pcse
        - git+https://github.com/jgomezdans/GomezEngine
        - git+https://github.com/jgomezdans/gp_emulator
        - prosail
