#!/bin/bash
jupyter nbextension enable --py widgetsnbextension
jupyter nbextension install --py --sys-prefix --overwrite ipympl
jupyter nbextension enable --py --sys-prefix ipympl

# Install a JupyterLab extension for demonstration purposes
#jupyter labextension install @jupyterlab/geojson-extension 
#jupyter labextension install @jupyter-widgets/jupyterlab-manager --minimise=False
#jupyter labextension install jupyter-leaflet
jupyter trust *.ipynb

