#!/bin/bash

jupyter contrib nbextension install --user
jupyter nbextension enable --py widgetsnbextension
jupyter nbextension enable python-markdown/main

# Install a JupyterLab extension for demonstration purposes
jupyter labextension install @jupyterlab/geojson-extension 
jupyter labextension install @jupyter-widgets/jupyterlab-manager --minimise=False
jupyter labextension install jupyter-leaflet
jupyter trust *.ipynb

